name: 'Build and Deploy'

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest
      
      - name: Deploy to Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest
      
      - name: Verify Pushed Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           sudo docker stop raghav1205/stock-ticker || true
           sudo docker rm raghav1205/stock-ticker || true
           sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest || true
           sudo docker pull ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest
           sudo docker run -d -p 8080:8080 --name stock-ticker -e STOCK_API_KEY=${{ secrets.STOCK_API_KEY }} ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest 
          - name: Deploy to EC2
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
               sudo docker stop raghav1205/stock-ticker || true
               sudo docker rm raghav1205/stock-ticker || true
               sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest || true
               sudo docker pull ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest
               sudo docker run -d -p 8080:8080 --name stock-ticker -e STOCK_API_KEY=${{ secrets.STOCK_API_KEY }} ${{ secrets.DOCKER_USERNAME }}/stock-ticker:latest 
               sudo docker stop raghav1205/redis || true
               sudo docker rm raghav1205/redis || true
               sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/redis:latest || true
               sudo docker pull ${{ secrets.DOCKER_USERNAME }}/redis:latest
               sudo docker run -d -p 6379:6379 redis 


